//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Battleships.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Battleships.UI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}&apos;s Ocean Grid.
        /// </summary>
        internal static string PlayerOceanGrid {
            get {
                return ResourceManager.GetString("PlayerOceanGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}&apos;s Targeting Grid.
        /// </summary>
        internal static string PlayerTargetingGrid {
            get {
                return ResourceManager.GetString("PlayerTargetingGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a position a ship will be placed. Choose a H or V (H - horizontal, V - vertical):.
        /// </summary>
        internal static string TypeDirection {
            get {
                return ResourceManager.GetString("TypeDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your name:.
        /// </summary>
        internal static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a point (e.g. A1 where A is a column and 1 is a row):.
        /// </summary>
        internal static string TypePoint {
            get {
                return ResourceManager.GetString("TypePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a start point (e.g. A1 where A is a column and 1 is a row):.
        /// </summary>
        internal static string TypeStartPoint {
            get {
                return ResourceManager.GetString("TypeStartPoint", resourceCulture);
            }
        }
    }
}
